### PR TITLE
package-lock

### PR DESCRIPTION
**Pull request by stanislavvdoviuk**

### CODE REVIEW

**Review by Borys-Menko — APPROVED** [review]

**Review by Borys-Menko — APPROVED** [review]

**Review by PavloTytarchuk — APPROVED** [review]
!

**Review by stadnytskyivp — APPROVED** [review]
good job

**Review by 51stRoR — APPROVED** [review]

**Review by AndrewRorat — APPROVED** [review]
Good job!

**Review by BorisTitarenko — APPROVED** [review]

**Review by BorisTitarenko — APPROVED** [review]

**Review by AndrewRorat — APPROVED** [review]
Good job!

**Review by LyubomyrKovch — APPROVED** [review]

**Pull request merged**
